# Generated by Django 5.0 on 2023-12-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc_cat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_cat',
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='описание категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
